defmodule ShelleyPlantsWeb.PlantImages do
  @moduledoc """
  Picks the right image file for a plant photo.

  Small displays (gallery cards, list thumbnails) should use `thumb_url/1`,
  which serves a downsized sRGB copy from `/images/plants/thumbs/` when one
  exists (generated by `scripts/make_plant_thumbnails.sh`), and falls back to
  the full-size photo otherwise — e.g. for a photo just uploaded via the admin
  form.
  """

  @plants_prefix "/images/plants/"

  def thumb_url(nil), do: nil

  def thumb_url(@plants_prefix <> filename = picture) do
    thumb = "thumbs/" <> Path.rootname(filename) <> ".jpg"

    if File.exists?(Path.join(plants_dir(), thumb)) do
      @plants_prefix <> thumb
    else
      picture
    end
  end

  def thumb_url(picture), do: picture

  defp plants_dir do
    Application.app_dir(:shelley_plants, ["priv", "static", "images", "plants"])
  end
end
